### ISSUE TITLE
globulation2.org is gone

### ISSUE THREAD

**Issue by masoudd** [Globulation2/glob2#101]
It just shows the default nginx welcome message. Do we have access to the domain name? Is there any plan to revive the site?

**Comment by stephanemagnenat** [comment]
So, it looks messy. The Gobulation2 domain was hosted by godaddy.com, which I renewed last time 13.11.21 for two years. However, godaddy.com seems not accessible nowadays.

The Wiki itself was on progval.net. @progval did you do any change on your side?

**Comment by progval** [comment]
My bad, I had a server outage two weeks ago and forgot to reconfigure the reverse proxy. It's back up now

**Comment by stephanemagnenat** [comment]
Thank you for the quick answer!
