### ISSUE TITLE
CPU load indicator reaches right edge of screen on a slow computer / under load

### ISSUE THREAD

**Issue by Quipyowert2** [Globulation2/glob2#102]
On my slow, 5-year-old laptop, I have several programs open at the same time. Globulation 2's indicator for whether the computer is running slow reaches the right edge of the window. It's only supposed to get to the vertical white line and stop.

Steps to reproduce:
1. Set your computer (or virtual machine) to a low clock speed
2. Start the tutorial in Glob2

What happens:
<details> 

<summary> The CPU load indicator glitch </summary>

![image](https://github.com/Globulation2/glob2/assets/38995150/6dea744d-c579-44b2-a293-6506344e5d08)

</details>

What I expected:
The CPU load indicator should stay in between the two vertical lines.

For quite a while, I actually thought this was a problem with the way I implemented resize in PR #64, but just noticed it on a lightly modded Globulation 2 today when I was trying to fix issue #80.

This happens with Globulation 2 beta4.5-574-g39980149 on Windows 10 Home 22H2 19045.3324 running on an MSI GS63 Stealth 8RE laptop. I have to set my laptop to run at the slowest mode: Eco, which is about 0.8 GHz or so, for it not to overheat. I'll probably have to buy a new computer pretty soon whenever this one decides to bite the dust.

**Comment by Quipyowert2** [comment]
Oh, this was a side effect of changing some stuff in Engine::run. Should I close this?

**Comment by Giszmo** [comment]
The CPU bar is supposed to over-shoot the first white line so there is no glitch in the overshoot. At 50%, the game runs at normal speed. At 200% it runs at half the speed. In a network game, one player running at 200% slows it down for all.
