### ISSUE TITLE
Crash with Invalid coordinate Y=127 for team 2 building 10 (swimmingpool) with Y span [-1:5[, healing!

### ISSUE THREAD

**Issue by Giszmo** [Globulation2/glob2#105]
I was just about to win when all of a sudden glob2 did not respond anymore and I had to kill it. Loading from the autosave reproduced the issue.

This crash is reproducible with latest master 39980149af3b1f2dd55eb53269a280a2913995bf

[CrashNicowar.zip](https://github.com/Globulation2/glob2/files/13391587/CrashNicowar.zip)

**Comment by Quipyowert2** [comment]
That message is from PR #84, which attempts to fix issue #44 by slightly adjusting the coordinates of the swimming pool. If the campaign editor was working, there would be a simple fix -- one would just have to load the map and then save it.

**Comment by Giszmo** [comment]
My particular issue was fixed with #106. As you suggest there are open PRs for that other open issue I will close this one meanwhile.
