### ISSUE TITLE
Game crashes end of campaign tutorial 4

### ISSUE THREAD

**Issue by waym0re** [Globulation2/glob2#119]
Globulation 2 - 0.9.4.4

Compiled on Aug 31 2023 at 14:21:45

Compiled with SDL version 1.2.64
Linked with SDL version 1.2.68
____

Near the end of the tutorial, when destroying the final buildings of the enemy, the game crashes (both regular and opengl), and the error is as follow:

glob2: src/Game.cpp:2201: void Game::drawMapGroundBuildings(int, int, int, int, int, int, int, int, int, Uint32, std::set<Building*>*): Assertion `building' failed.
Aborted (core dumped)

Using the Arch package in the regular repo (aka pacman -S glob2).

**Comment by Quipyowert2** [comment]
Does this happen when destroying a racetrack? If so, this is bug #44 which there is a workaround for in PR #84 which stops it from crashing.

Does it still happen when using Globulation 2 compiled from latest master?

There hasn't been a release in quite some time, see discussion in #76 about whether to release yet or not.

**Comment by waym0re** [comment]
Yes, I'm sorry, indeed the latest compilation works, and it does seem related to the racetrack in the map editor. Closing the issue.
