### ISSUE TITLE
SConscript files for python 3

### ISSUE THREAD

**Issue by cajomar** [Globulation2/glob2#24]
When I tried compiling I got an error because the scons files were for python 2.  
So I gave them 3.x syntax for them and also the python files in `src/`.    
Do you want me to make a pull request for that?

**Comment by spikebike** [comment]
I'm not in the project, but sure, sounds like a good idea.  As a bonus when you fork it people will be able to access it.

**Comment by stephanemagnenat** [comment]
This is merged in 3dd1b31d90c7ad44baa67bdbfbfd8bbb1feff857, closing.
