### ISSUE TITLE
Add link to github in Wiki for "View Bugs"

### ISSUE THREAD

**Issue by stephanemagnenat** [Globulation2/glob2#34]
@ProgVal I do not have access it the [SideBar of MediaWiki](https://globulation2.org/wiki/MediaWiki:Sidebar). Could you change "View Bugs" to point to `https://github.com/Globulation2/glob2/issues` and keep the current one as "(old)"? Thank you!

**Comment by ProgVal** [comment]
You should have the rights now

**Comment by stephanemagnenat** [comment]
Thanks, update done!
