### ISSUE TITLE
Suggest: rename README to README.md

### ISSUE THREAD

**Issue by richelbilderbeek** [Globulation2/glob2#8]
Currently, the README shows the link to the Globulation 2 website as plain-text:

![improment](https://user-images.githubusercontent.com/2098230/71543108-ac79e600-296f-11ea-9a46-8d38c27941da.png)

I suggest to allow for Markdown formatting, by renaming README to README.md.

I volunteer to do so, though it is kind of trivial to do :grin:

**Comment by randomvoids** [comment]
Done, thanks!
